#!/usr/bin/env python3
"""Enforce the repository's soft-wrap house style on Markdown prose.

House style (see logbook/README.md and CLAUDE.md): every paragraph, list item
and blockquote occupies exactly one physical line. Prose is *not* hard-wrapped
at a column width — the editor wraps it for display. Headings, tables, thematic
breaks (`---`), fenced and indented code, and HTML blocks are exempt.

    python scripts/check_softwrap.py [PATH ...]        # report, exit 1 on any
    python scripts/check_softwrap.py --fix [PATH ...]  # unwrap in place

With no PATH, every tracked-looking `*.md` under the repo root is checked except
the generated and verbatim files listed in EXCLUDE: the CC-BY licence text is a
distributed legal document, and codebook.md / views/*.md are regenerated by
their build scripts, which is where their wrapping would have to change.
"""
from __future__ import annotations

import argparse
import fnmatch
import re
import sys
from pathlib import Path

from markdown_it import MarkdownIt

REPO = Path(__file__).resolve().parent.parent

# Paths (relative to the repo root, forward slashes) that the house style does
# not govern because nobody hand-wraps them: a verbatim licence, and generated
# files whose wrapping lives in the generator.
EXCLUDE = [
    "LICENSE-DATA.md",
    "datasets/*/codebook.md",
    "views/*.md",
]

_MD = MarkdownIt("commonmark").enable("table")
_BQ_PREFIX = re.compile(r"^\s*(?:>\s?)+")


def _excluded(rel: str) -> bool:
    return any(fnmatch.fnmatch(rel, pat) for pat in EXCLUDE)


def discover() -> list[Path]:
    out = []
    for p in sorted(REPO.rglob("*.md")):
        if ".git/" in p.as_posix():
            continue
        rel = p.relative_to(REPO).as_posix()
        if not _excluded(rel):
            out.append(p)
    return out


def wrapped_paragraphs(lines: list[str]) -> list[tuple[int, int]]:
    """Return (start_line, end_line) 1-based inclusive spans of every paragraph
    token whose source covers more than one non-blank physical line."""
    spans = []
    for tok in _MD.parse("\n".join(lines)):
        if tok.type != "paragraph_open" or not tok.map:
            continue
        s, e = tok.map  # 0-based, end exclusive
        nonblank = [i for i in range(s, min(e, len(lines))) if lines[i].strip()]
        if len(nonblank) > 1:
            spans.append((nonblank[0] + 1, nonblank[-1] + 1))
    return spans


def unwrap(lines: list[str], span: tuple[int, int]) -> str:
    """Join the physical lines of one paragraph span into a single line,
    keeping the first line's leading indent and any blockquote marker."""
    start, end = span
    first = lines[start - 1]
    lead = first[: len(first) - len(first.lstrip())]
    bq = _BQ_PREFIX.match(first)
    # The blockquote marker (one level, normalised) or the plain indent is
    # carried once, on the rebuilt line; every source line then contributes only
    # its text, with any `>` markers and wrap indentation stripped.
    prefix = bq.group(0).rstrip() + " " if bq else lead
    pieces = []
    for i in range(start - 1, end):
        text = _BQ_PREFIX.sub("", lines[i]).strip()
        if text:
            pieces.append(text)
    return prefix + " ".join(pieces)


def _rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO).as_posix()
    except ValueError:
        return str(path)


def process(path: Path, fix: bool) -> int:
    lines = path.read_text(encoding="utf-8").split("\n")
    spans = wrapped_paragraphs(lines)
    if not spans:
        return 0
    rel = _rel(path)
    if not fix:
        for start, end in spans:
            preview = lines[start - 1].strip()[:78]
            print(f"{rel}:{start}: paragraph spans {end - start + 1} lines — {preview}")
        return len(spans)
    for start, end in sorted(spans, reverse=True):
        joined = unwrap(lines, (start, end))
        lines[start - 1 : end] = [joined]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"{rel}: unwrapped {len(spans)} paragraph(s)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="*", type=Path, help="Markdown files to check (default: all in-scope *.md)")
    ap.add_argument("--fix", action="store_true", help="rewrite files, unwrapping each offending paragraph")
    args = ap.parse_args()

    if args.paths:
        targets = []
        for p in args.paths:
            if p.is_dir():
                targets += [q for q in sorted(p.rglob("*.md"))
                            if not _excluded(q.resolve().relative_to(REPO).as_posix())]
            else:
                targets.append(p)
    else:
        targets = discover()

    violations = 0
    checked = 0
    for path in targets:
        path = path.resolve()
        if not path.exists():
            print(f"warning: {path} does not exist", file=sys.stderr)
            continue
        checked += 1
        violations += process(path, args.fix)

    if args.fix:
        return 0
    if violations:
        print(f"\n{violations} hard-wrapped paragraph(s). Run: python scripts/check_softwrap.py --fix", file=sys.stderr)
        return 1
    print(f"{checked} file(s) OK — no hard-wrapped prose.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
